[setup]
boxlength         = {BOXLENGTH}  # in Mpc/h
zstart            = {ZSTART}     # starting redshift
levelmin          = {LEVEL}      # log2(N); sets grid resolution N = 2^levelmin per side
levelmin_TF       = {LEVEL}      # transfer function grid (same as levelmin for uniform runs)
levelmax          = {LEVEL}      # levelmax = levelmin for uniform (no zoom) runs
padding           = 8            # cells used for padding at refinement boundary
ref_center        = 0.5, 0.5, 0.5
ref_extent        = 0.2, 0.2, 0.2
align_top         = no
baryons           = no
use_2LPT          = yes
fix_mode_amplitude = yes

[cosmology]
Omega_m           = 0.3
Omega_L           = 0.7
w_0               = -1.0
w_a               = 0.0
Omega_b           = 0.049
H0                = 67.11
sigma_8           = 0.8
n_s               = 0.9624
Tcmb              = 2.7255
k_p               = 0.05
N_ur              = 3.046
m_nu1             = 0.0
m_nu2             = 0.0
m_nu3             = 0.0
ZeroRadiation     = true
transfer          = CLASS
ztarget           = 0.0   # CLASS output at ztarget is back-scaled to zstart

[random]
seed[7]           = 66345
seed[8]           = 23346
seed[9]           = 34667
seed[10]          = 46238
seed[11]          = 56789
seed[12]          = 67890
rngfname          = data/wnoise_{LEVEL_PAD}.bin

[output]
format            = swift
filename          = {FILENAME}
